Repository Fun-d-6th-Stock-King/should-have-bought-app, pull requests merged in 2021-04, with the labels that each got.

#15 Feature/14
  assets/icons/Card.png
  assets/icons/Profile.png
  assets/icons/atm_location.png
  assets/icons/home.png
  assets/icons/home_white.png
  assets/icons/search.png
  lib/constant.dart
  lib/main.dart
  lib/screens/buy_or_not/buy_or_not_screen.dart
  lib/screens/card/card_screen.dart
  lib/screens/main/main_screen.dart
  lib/screens/my_page/my_page_screen.dart
  lib/screens/tab_screen.dart
  lib/screens/today_word/today_word_screen.dart
  pubspec.yaml
Labels: APP : Screen, Tab: 메인

#22 랜덤 버튼 구현, appbar 제거 -> Container로 변경, Autotext 적용
  lib/models/calculator/calculator_stock.dart
  lib/providers/calculator/calculator_provider.dart
  lib/screens/main/calculator_result_screen.dart
  pubspec.yaml
Labels: APP : UI, APP : 기능 수정

#24 Feature/13
  lib/screens/main/calculator_result_screen.dart
Labels: APP : 기능 수정

#28 [Master] Merge to Release/1.0
  android/app/build.gradle
  android/app/proguard-rules.pro
  android/app/src/debug/AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/kotlin/com/example/should_have_bought_app/MainActivity.kt
  android/app/src/profile/AndroidManifest.xml
  lib/api/api.dart
  lib/main.dart
  lib/screens/main/calculator_result_screen.dart
  lib/widgets/calculator/calculator_widget.dart
Labels: Release, 완료

#27 [Develop] Merge to Release/1.0
  android/app/build.gradle
  android/app/proguard-rules.pro
  android/app/src/debug/AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/kotlin/com/example/should_have_bought_app/MainActivity.kt
  android/app/src/profile/AndroidManifest.xml
  lib/api/api.dart
  lib/main.dart
  lib/screens/main/calculator_result_screen.dart
  lib/widgets/calculator/calculator_widget.dart
Labels: Release, 완료
